### ISSUE TITLE
About ResNet_30s_34lay_16conv.hdf5

### ISSUE THREAD

**Issue by weihhh** [fernandoandreotti/cinc-challenge2017#10]
Hi，
I have implemented your DL method  and used ResNet_30s_34lay_16conv.hdf5 model to classify all training data(8528), get mean F1 0.6117. But the [result](https://physionet.org/challenge/2017/results_all_F1_scores_for_each_classification_type.csv) shows your model should get F1 0.92 on training data. I am very confused about the difference.

**Comment by fernandoandreotti** [comment]
Hi,

I have indeed generated another model since the challenge with some added regularization and small changes. This should lead to small differences but not by this margin. Here are some thing you might think about:

1) Are you taking noise ('~') into consideration? The Challenge usually did not, therefore results are generally optimistic.
2) Are you training the model yourself? I used an augmented database for doing so, thus, achieving higher performance.
3) The good thing about the challenge is that everybody's code is accessible [(see here)](https://physionet.org/challenge/2017/sources/). You may try the exact model I submitted back then, however I believe the current one should perform slightly better.
